#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts wow_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ wow_hosts
echo "8.8.8.8 facebook.com" >> wow_hosts
cp wow_hosts /etc/hosts
